title: Homem Racional. 
description: Consciência e Racionalidade como uma manifestação dos valores humanos verossímeis e concretos.
url: https://homemracional.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Quem Somos
   url: /about
 - title: Contato
   url: /contact

social:
   github:
   twitter: 
   facebook: HomemRacional
   email: homem.racional.omega@gmail.com

google_analytics: "UA-58263416-1"
