title: Homem Racional | Frase aqui....
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Quem Somos
   url: /about
 - title: Contact
   url: /contact

social:
   github:
   twitter: 
   facebook: HomemRacional
   email: homem.racional.omega@gmail.com

google_analytics: "UA-58263416-1"
